using Dapper.Contrib.Extensions;
using EbaySharp.Entities.Develop.KeyManagement.SigningKey;
using System;
using System.Collections.Generic;
using System.Text;

namespace LocalDBConnections.StampDataDB.StampDataEntities
{
    //[Table("FeeBaySigningKey")]
    public class FeeBaySigningKeys
    {
        [Key]
        public string SigningKeyId { get; set; }
        public SigningKeyCipher? SigningKeyCipher { get; set; }
        public string? PublicKey { get; set; }

        public string? PrivateKey { get; set; }
        public string? JWE { get; set; }
        public int? CreationTime { get; set; }
        public int? ExpirationTime { get; set; }
        //a signing key is not associated directly
        //with a single buyer or seller user ID.
        //Instead, API signing keys (using the eBay Key Management API)
        //are tied to an Application created by a developer.
        //Here is how user authentication and keys work on the platform:
        //
        //Application Level: Signing keys (Public/Private key pairs) are
        //generated by developers to create secure digital signatures for
        //making API requests. They authenticate the app.

        //User Level: Individual user identity is handled through OAuth tokens.
        //To act on behalf of a specific user ID (like a seller account),
        //your app must obtain a User Access Token that associates
        //that specific user's authorization with your application's actions.
    }
}
